##                          ##
##         BlueMap          ##
##       Core-Config        ##
##                          ##

accept-download: true
data: "/app/data"
render-thread-count: 1
render-thread-priority: 1
scan-for-mod-resources: false
metrics: false
log: {
  # file: "/app/data/logs/debug.log"
  append: false
}