##                          ##
##         BlueMap          ##
##      Plugin-Config       ##
##                          ##

live-player-markers: true
hidden-game-modes: ["spectator"]
hide-vanished: true
hide-invisible: true
hide-sneaking: false
hide-below-sky-light: 0
hide-below-block-light: 0
hide-different-world: false
# write-markers-interval: 10
# write-players-interval: 3
skin-download: true
player-render-limit: -1
full-update-interval: 1440