##                          ##
##         BlueMap          ##
##      Webapp-Config       ##
##                          ##

enabled: true
webroot: "/app/web"
update-settings-file: true
use-cookies: true
default-to-flat-view: true
min-zoom-distance: 5
max-zoom-distance: 100000
resolution-default: 2
hires-slider-max: 500
hires-slider-default: 100
hires-slider-min: 0
lowres-slider-max: 7000
lowres-slider-default: 2000
lowres-slider-min: 500
scripts: []
styles: []