##                          ##
##         BlueMap          ##
##     Webserver-Config     ##
##                          ##

enabled: true
webroot: "/app/web"
port: 8100
log: {
  file: "/app/data/logs/webserver.log"
  append: false
  format: "%1$s \"%3$s %4$s %5$s\" %6$s %7$s"
}