upstream backend {
    server yea_backend:8000;
}

upstream frontend {
    server yea_frontend:3000;
}

server {
    listen 80;
    server_name cubethrone.fun www.cubethrone.fun;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name cubethrone.fun www.cubethrone.fun;

    ssl_certificate /etc/letsencrypt/live/cubethrone.fun/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cubethrone.fun/privkey.pem;

    client_max_body_size 20M;

    location /map/ {
        alias /var/www/bluemap/;
        try_files $uri /map/sql.php?$args;
    }
    
    location ~ /map/.*\.php$ {
        fastcgi_pass bluemap_php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/bluemap$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME /map$fastcgi_script_name;
        include fastcgi_params;
    }


    location /admin/ {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /swagger/ {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /redoc/ {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /swagger.json {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /swagger.yaml {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /static/ {
        alias /app/static/;
    }

    location /media/ {
        alias /app/media/;
    }

    location /installer/ {
        alias /app/installer/;
        autoindex off;
        add_header Accept-Ranges bytes;
        sendfile on;
        tcp_nopush on;
    }

    location /api/ {
        if ($http_referer !~* "^https://(cubethrone\.fun|www\.cubethrone\.fun)") {
            return 403;
        }

        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }


    location / {
        proxy_pass http://frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }


}
