upstream backend {
    server yea_backend:8000;
}

upstream frontend {
    server yea_frontend:3000;
}

server {
    listen 80;
    server_name cubethrone.fun www.cubethrone.fun;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name cubethrone.fun www.cubethrone.fun;

    ssl_certificate /etc/letsencrypt/live/cubethrone.fun/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cubethrone.fun/privkey.pem;

    client_max_body_size 20M;

    location /admin/ {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /swagger/ {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /redoc/ {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /swagger.json {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /swagger.yaml {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /static/ {
        alias /app/static/;
    }

    location /media/ {
        alias /app/media/;
    }

    location /installer/ {
        alias /app/installer/;
        autoindex off;
        add_header Accept-Ranges bytes;
        sendfile on;
        tcp_nopush on;
    }

    location /api/ {
        if ($http_referer !~* "^https://(cubethrone\.fun|www\.cubethrone\.fun)") {
            return 403;
        }

        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /maps/ {
        # Направляем все запросы сразу в PHP, минуя проверку файлов на диске
        fastcgi_pass yea_bluemap:9000;
        
        # Обманываем скрипт, чтобы он думал, что лежит в корне
        fastcgi_param SCRIPT_NAME /sql.php;
        fastcgi_param SCRIPT_FILENAME /var/www/bluemap/sql.php;
        
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_param DOCUMENT_ROOT /var/www/bluemap;
        fastcgi_param HTTPS on;
        include fastcgi_params;
    }

    location @bluemap_php {
        fastcgi_pass yea_bluemap:9000;
        
        # Важно: SCRIPT_NAME должен быть /sql.php, чтобы $root стал пустым
        fastcgi_param SCRIPT_NAME /sql.php;
        fastcgi_param SCRIPT_FILENAME /var/www/bluemap/sql.php;
        
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_param DOCUMENT_ROOT /var/www/bluemap;
        fastcgi_param HTTPS on;
        include fastcgi_params;
    }


    location / {
        proxy_pass http://frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }


}
