# Generated by Django 4.2.16 on 2026-06-24 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_token_is_vip_vipurl_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Опишите вашу проблему или вопрос', verbose_name='Текст обращения')),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('approved', 'Принято'), ('rejected', 'Отклонено')], default='processing', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='users.siteuser', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['author', 'status'], name='tickets_tic_author__7ad27f_idx'), models.Index(fields=['created_at'], name='tickets_tic_created_5dd600_idx')],
            },
        ),
    ]
