services:
  db:
    image: postgres:16-alpine
    container_name: yea_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - yea_network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: yea_backend
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - yea_network
    command: >
      sh -c "
      while ! pg_isready -h db -p 5432 -U ${POSTGRES_USER}; do sleep 1; done &&
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0.0.0.0:8000 yea_project.wsgi:application
      "

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: yea_frontend
    volumes:
      - ../frontend/src:/app/src
      - ../frontend/public:/app/public
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - yea_network

  bluemap:
    image: ghcr.io/bluecolored/bluemap:latest
    container_name: yea_bluemap
    ports:
      - "8100:8100"  # Порт для доступа к BlueMap
    volumes:
      - ../bluemap:/bluemap:rw  # Монтируем всю папку bluemap для доступа к конфигам и данным
    environment:
      # Переменные для подключения к базе данных
      - DB_HOST=${BLUEMAP_DB_HOST}
      - DB_PORT=${BLUEMAP_DB_PORT}
      - DB_USER=${BLUEMAP_DB_USER}
      - DB_NAME=${BLUEMAP_DB_NAME}
      - DB_PASSWORD=${BLUEMAP_DB_PASSWORD}
      # Дополнительные переменные для BlueMap
      - WEB_PORT=8100
      - WEB_IP=0.0.0.0
    depends_on:
      - db
    networks:
      - yea_network
    restart: unless-stopped
  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    container_name: yea_gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /opt/data:/app/installer:ro
      - ./bluemap-nginx.conf:/etc/nginx/conf.d/bluemap.conf:ro
    depends_on:
      - backend
      - frontend
      - bluemap
    networks:
      - yea_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  yea_network:
    driver: bridge
