webserver: {
  ip: "0.0.0.0"
  port: 8100
}

webapp: {
  title: "BlueMap"
  # Если вам нужно переопределить, используйте переменные
}

# Убедитесь, что указываете правильный путь к картам
maps: {
  root: "/bluemap/maps"
}