worker_processes auto;
error_log /dev/stderr info;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    
    access_log /dev/stdout;

    server {
        listen 80;
        server_name _;
        
        # Корневая директория, куда смонтированы файлы BlueMap
        root /var/www/bluemap;
        index index.html;

        # Основной блок location
        location / {
            # Сначала пробуем найти файл по URI ($uri)
            # Если файла нет, пробуем директорию ($uri/)
            # Если и этого нет, переписываем запрос на sql.php
            try_files $uri $uri/ /sql.php?$query_string;
        }

        # Обработка PHP файлов
        location ~ \.php$ {
            # Проверка существования файла перед передачей в FPM
            try_files $uri =404;
            
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index sql.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            include fastcgi_params;
        }
    }
}