# bluemap/webapp.conf
webapp {
    # Порт на котором будет работать веб-интерфейс
    port = 8100
    host = "0.0.0.0"
    
    # Корневая директория для веб-файлов
    webroot = "web"
    
    # Если используете прокси-сервер (nginx)
    proxy-path = "/bluemap"
}