##                          ##
##         BlueMap          ##
##      Storage-Config      ##
##                          ##

# The storage-type of this storage.
storage-type: sql

# MySQL JDBC Connection URL
connection-url: "jdbc:mysql://${env.BLUEMAP_DB_HOST}:${env.BLUEMAP_DB_PORT}/${env.BLUEMAP_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true"

# Connection properties
connection-properties: {
  user: "${env.BLUEMAP_DB_USER}",
  password: "${env.BLUEMAP_DB_PASSWORD}"
}

# Maximum connections
max-connections: -1

# Driver class for MySQL
driver-class: "com.mysql.cj.jdbc.Driver"

# Compression type
compression: gzip