# ./bluemap/config/storages/sql.conf
storage-type: sql

# MariaDB/MySQL URL
connection-url: "jdbc:mariadb://${env.BLUEMAP_DB_HOST}:${env.BLUEMAP_DB_PORT}/${env.BLUEMAP_DB_NAME}"

connection-properties: {
    user: "${env.BLUEMAP_DB_USER}",
    password: "${env.BLUEMAP_DB_PASSWORD}",
    useSSL: "false"
}

pool-size: 10
connection-timeout: 30000

# Если нужен отдельный драйвер (обычно не требуется для Paper, но для других сред может понадобиться)
# driver-jar: "bluemap/mariadb-java-client.jar"
# driver-class: "org.mariadb.jdbc.Driver"