# Generated by Django 4.2.16 on 2026-04-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
