# Generated by Django 4.2.16 on 2026-04-13 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_siteuser_is_active_remove_siteuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'vip_status': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tokens', to='users.siteuser', verbose_name='Владелец (VIP)'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='nickname',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ник'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='registered_with_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.token', verbose_name='Токен регистрации'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='vip_status',
            field=models.BooleanField(default=False, verbose_name='VIP статус'),
        ),
        migrations.AlterField(
            model_name='token',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='token',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=32, unique=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='token',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата использования'),
        ),
        migrations.AlterField(
            model_name='token',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_tokens', to='users.siteuser', verbose_name='Использован пользователем'),
        ),
    ]
