# Generated by Django 4.2.16 on 2026-05-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_token_owner_alter_siteuser_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('vip', models.ForeignKey(limit_choices_to={'vip_status': True}, on_delete=django.db.models.deletion.CASCADE, related_name='vip_urls', to='users.siteuser', verbose_name='VIP пользователь')),
            ],
            options={
                'verbose_name': 'VIP URL',
                'verbose_name_plural': 'VIP URLs',
            },
        ),
    ]
