# Generated by Django 4.2.16 on 2026-06-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_vipurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='VIP токен'),
        ),
        migrations.AddField(
            model_name='vipurl',
            name='title',
            field=models.CharField(default=False, max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
